@echo off
SETLOCAL ENABLEEXTENSIONS
setlocal enableDelayedExpansion

cls

IF "%1" EQU "" (
    SET BUILD_CONFIGURATION=All-x64-Debug
) ELSE (
    SET BUILD_CONFIGURATION=%1
)

SET DEFAULT_ADDITIONAL_PARAMETERS=-dist -summary -monitor

IF "%2" EQU "" (
    SET ADDITIONAL_PARAMETERS=%DEFAULT_ADDITIONAL_PARAMETERS%
) ELSE (
    SET ADDITIONAL_PARAMETERS=%DEFAULT_ADDITIONAL_PARAMETERS% %2
)

cd %INSIGHTFUL_DEV_DIR%

REM SHOW INVERTED CONSOLE WINDOW WHILE BUILDING
color F0
REM SHOW BLUE WINDOW WHILE BUILDING
color 1f

@echo on

%FASTBUILD_ROOT_DIR%\FBuild.exe %ADDITIONAL_PARAMETERS% %BUILD_CONFIGURATION%

@echo off

IF %ERRORLEVEL% EQU -1 (
  REM SHOW RED SCREEN ON FAILURE
  color 4F
) ELSE (
  REM SHOW GREEN SCREEN ON SUCCESS
  color 2F
)

ECHO.
ECHO ***** Finished invoking FastBuild on Configuration: %BUILD_CONFIGURATION% *****
ECHO.
pause

REM RESTORE NORMAL CONSOLE WINDOW COLORS
color 0f
GOTO :EOF